#!/bin/sh /etc/rc.common

USE_PROCD=1
START=55

CONFIGURATION=thermal_metrics

start_service() {
  # Reading config
  config_load "${CONFIGURATION}"
  local interval

  config_get interval general interval

  procd_open_instance
  procd_set_param command "/usr/local/bin/thermal_metrics_update.sh" "$interval"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_set_param file /etc/config/thermal_metrics
  procd_close_instance
}
